%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 596.1950425915236
Camera1.fy: 593.1411835433107
Camera1.cx: 327.0463454538411
Camera1.cy: 245.16142133264628

Camera1.k1: 0.07561607662577634
Camera1.k2: -0.2088729975389971
Camera1.p1: -0.0023347441072184756
Camera1.p2: 0.004010356017731083

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Transformation from left camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ -0.01380329, -0.00268973,  0.99990111,  0.39264867, 
           -0.99970536,  0.02000557, -0.01374677,  0.18976477, 
           -0.01996661, -0.99979625, -0.00296508, -0.01649762, 
            0.00000000,  0.00000000,  0.00000000,  1.00000000 ]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 57

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.0010803000133061877  # rad/s^0.5
IMU.NoiseAcc: 0.022943696261362133  # m/s^1.5
IMU.GyroWalk: 1.0473874193084336e-06  # rad/s^1.5
IMU.AccWalk: 0.0001591704479239952  # m/s^2.5
IMU.Frequency: 130.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.0745

# Depth map values factor
RGBD.DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1800

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 5

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

