%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 377.76416031338175
Camera1.fy: 376.7568882737175
Camera1.cx: 324.43054459524114
Camera1.cy: 237.7835851919431

Camera1.k1: -0.06157226554259826
Camera1.k2: 0.034399973844349424
Camera1.p1: -0.0008061851770185934
Camera1.p2: -0.0007949203741555398

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 30

# Transformation from left camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [  0.00418799, -0.01506274,  0.99987778,  0.39248015, 
           -0.99997679, -0.00543574,  0.00410652,  0.15686652, 
            0.00537322, -0.99987178, -0.01508516, -0.03767881, 
            0.00000000,  0.00000000,  0.00000000,  1.00000000 ]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 57

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.0005401500066530939  # rad/s^0.5
IMU.NoiseAcc: 0.011471848130681066  # m/s^1.5
IMU.GyroWalk: 1.0473874193084335e-05  # rad/s^1.5
IMU.AccWalk: 0.001591704479239952  # m/s^2.5
IMU.Frequency: 65.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.0745

# Depth map values factor
RGBD.DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

