%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "KannalaBrandt8"

# Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 280.4362476646957
Camera1.fy: 279.5757903173993
Camera1.cx: 434.5911290024899
Camera1.cy: 395.3741210501516

# Kannala-Brandt distortion parameters
Camera1.k1: -0.011532772136434897
Camera1.k2: 0.0501515488043061
Camera1.k3: -0.05041450901368907
Camera1.k4: 0.012741893876582578

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 280.311263999059
Camera2.fy: 279.5434630904508
Camera2.cx: 431.35302371548494
Camera2.cy: 388.5071222043099

# Kannala-Brandt distortion parameters
Camera2.k1: -0.011950967309164085
Camera2.k2: 0.0530642563172375
Camera2.k3: -0.049469178559530994
Camera2.k4: 0.011573768486635416
    
# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [  0.999962395000,  0.006979572420,  0.005147684990,  0.063473707300, 
           -0.006993187680,  0.999972086000,  0.002632150260, -0.000846443040, 
           -0.005129175010, -0.002668049790,  0.999983283000,  0.000580864703, 
            0.000000000000,  0.000000000000,  0.000000000000,  1.000000000000 ]

# Lapping area between images (We must calculate)
Camera1.overlappingBegin: 0
Camera1.overlappingEnd: 848

Camera2.overlappingBegin: 0
Camera2.overlappingEnd: 848

# Camera resolution
Camera.width: 848
Camera.height: 800

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 100.0

# Transformation from left camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ -0.99997902,  0.00112864, -0.00637861,  0.00846283, 
           -0.00125944, -0.99978827,  0.02053873,  0.00361661, 
           -0.00635408,  0.02054633,  0.99976871,  0.00146200, 
            0.00000000,  0.00000000,  0.00000000,  1.00000000 ]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 57

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 0.003235643391462107  # rad/s^0.5
IMU.NoiseAcc: 0.017406273886926244  # m/s^1.5
IMU.GyroWalk: 7.056778665898092e-05  # rad/s^1.5
IMU.AccWalk: 0.012393508837042726  # m/s^2.5
IMU.Frequency: 265.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 15
ORBextractor.minThFAST: 5

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
